# Generated by Django 3.2.3 on 2021-06-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingponghit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.AddField(
            model_name='pingponghit',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
