# Generated by Django 3.2.3 on 2021-06-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingponghit', '0002_auto_20210605_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingponghit',
            name='total',
        ),
    ]
