# Generated by Django 3.2.3 on 2021-06-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingponghit', '0004_pingponghit_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalhit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='pingponghit',
            name='total',
        ),
    ]
