# Generated by Django 3.2.3 on 2021-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingponghit', '0005_auto_20210611_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalhit',
            name='hitavg',
            field=models.IntegerField(default=0),
        ),
    ]
