# Generated by Django 3.2.3 on 2021-06-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingponghit', '0006_totalhit_hitavg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalhit',
            old_name='hitavg',
            new_name='hitCavg',
        ),
        migrations.AddField(
            model_name='totalhit',
            name='hitHavg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='totalhit',
            name='hitLavg',
            field=models.IntegerField(default=0),
        ),
    ]
